/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import JFrames.TextPrompt;
import Logica.datos;
import Tipografia.Fuente;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Reyes
 */
public class panelVendedores extends javax.swing.JPanel {

    /**
     * Creates new form panelVendedores
     */
    Fuente tipoFuente;
    public panelVendedores() {
        initComponents();
        
        tipoFuente = new Fuente();
        txtnombre.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        txtcelular.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        txtsueldo.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        txtdireccion.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        txtidvendedor1.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        txtcorreo.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        cbojornada.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 12));
        cbodocu.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 12));
        L1.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        L2.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        L3.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        L4.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        L5.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        L6.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        cbojornada = new javax.swing.JComboBox();
        cbodocu = new javax.swing.JComboBox();
        txtdireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JLabel();
        btnguardar = new javax.swing.JLabel();
        btneditar = new javax.swing.JLabel();
        btneliminar = new javax.swing.JLabel();
        txtidvendedor1 = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(61, 61, 61));
        setOpaque(false);

        L1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setText("ID VENDEDOR");

        L2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L2.setForeground(new java.awt.Color(255, 255, 255));
        L2.setText("NOMBRE");

        L3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L3.setForeground(new java.awt.Color(255, 255, 255));
        L3.setText("DIRECCION");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID JORNADA");

        L4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L4.setForeground(new java.awt.Color(255, 255, 255));
        L4.setText("SUELDO");

        L6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L6.setForeground(new java.awt.Color(255, 255, 255));
        L6.setText("NUMERO CELULAR");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID TIPO DOCUMENTO");

        L5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L5.setForeground(new java.awt.Color(255, 255, 255));
        L5.setText("CORREO");

        cbojornada.setForeground(new java.awt.Color(0, 0, 0));
        cbojornada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR", "MATUTINA\t", "DIIURNA", "NOCTURNA" }));
        cbojornada.setPreferredSize(new java.awt.Dimension(166, 26));
        cbojornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojornadaActionPerformed(evt);
            }
        });

        cbodocu.setForeground(new java.awt.Color(0, 0, 0));
        cbodocu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCONAR", "TARJETA DE IDENTIDAD ", "PASAPORTE ", "RTN" }));

        txtdireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtdireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdireccion.setOpaque(false);

        jTable1.setBackground(new java.awt.Color(61, 61, 61));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VendedoresLT 1.png"))); // NOI18N

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnNuevo.png"))); // NOI18N
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoMouseClicked(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar.png"))); // NOI18N
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEditar.png"))); // NOI18N
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditarMouseClicked(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEliminar.png"))); // NOI18N
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });

        txtidvendedor1.setForeground(new java.awt.Color(255, 255, 255));
        txtidvendedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidvendedor1.setOpaque(false);

        txtcelular.setForeground(new java.awt.Color(255, 255, 255));
        txtcelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcelular.setOpaque(false);

        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setOpaque(false);

        txtsueldo.setForeground(new java.awt.Color(255, 255, 255));
        txtsueldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsueldo.setOpaque(false);

        txtcorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtcorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtidvendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(L1)
                .addGap(212, 212, 212)
                .addComponent(L2)
                .addGap(223, 223, 223)
                .addComponent(L3))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(L4)
                .addGap(232, 232, 232)
                .addComponent(L5)
                .addGap(199, 199, 199)
                .addComponent(L6))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(cbodocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(cbojornada, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel8)
                .addGap(187, 187, 187)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnnuevo)
                .addGap(35, 35, 35)
                .addComponent(btnguardar)
                .addGap(35, 35, 35)
                .addComponent(btneditar)
                .addGap(35, 35, 35)
                .addComponent(btneliminar))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidvendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L1)
                            .addComponent(L3))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(L4))
                    .addComponent(L5)
                    .addComponent(L6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbodocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbojornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btneditar)
                    .addComponent(btneliminar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbojornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbojornadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbojornadaActionPerformed

    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked
       boolean guardo = true;
        datos data = new datos();
        data.setIDVendedor(Integer.parseInt(txtdireccion.getText()));
        data.setNombre(txtnombre.getText());
        data.setDireccion(txtdireccion.getText());
        data.setSueldo(Float.parseFloat(txtsueldo.getText()));
        data.setIDJornada(Integer.parseInt(cbojornada.getActionCommand()));
        data.setNumeroCelular(Integer.parseInt(txtcelular.getText()));
        data.setIDTipoDocumento(Integer.parseInt(cbodocu.getActionCommand()));
          
        guardo = data.guardar();
        if (guardo==true){
            JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente");
        }
    }//GEN-LAST:event_btnguardarMouseClicked

    private void btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMouseClicked
        boolean edito = true;
        datos data = new datos();
        data.setIDVendedor(Integer.parseInt(txtdireccion.getText()));
        data.setNombre(txtnombre.getText());
        data.setDireccion(txtdireccion.getText());
        data.setSueldo(Float.parseFloat(txtsueldo.getText()));
        data.setIDJornada(Integer.parseInt(cbojornada.getActionCommand()));
        data.setNumeroCelular(Integer.parseInt(txtcelular.getText()));
        data.setIDTipoDocumento(Integer.parseInt(cbodocu.getActionCommand()));
        data.editar();
        if (edito==true){
            JOptionPane.showMessageDialog(null, "Datos Editados Correctamente");
        }
    }//GEN-LAST:event_btneditarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        boolean elimino = true;       
        datos data = new datos();
        data.setIDVendedor(Integer.parseInt(txtdireccion.getText()));
        data.eliminar();
        if (elimino==true){
            JOptionPane.showMessageDialog(null, "Datos Eliminados Correctamente");
        }
    }//GEN-LAST:event_btneliminarMouseClicked

    private void btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseClicked
       txtdireccion.setText("");
        txtnombre.setText("");
        txtidvendedor1.setText("");
        txtdireccion.setText("");
        txtsueldo.setText("");
        txtcelular.setText("");
        txtcorreo.setText("");
        btnguardar.setEnabled(true);
        
    }//GEN-LAST:event_btnnuevoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel btneditar;
    private javax.swing.JLabel btneliminar;
    private javax.swing.JLabel btnguardar;
    private javax.swing.JLabel btnnuevo;
    private javax.swing.JComboBox cbodocu;
    private javax.swing.JComboBox cbojornada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidvendedor1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
