/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Paneles.panelAcercaDe;
import Paneles.panelHistorial;
import Paneles.panelInicio;
import Paneles.panelPeliculas;
import Paneles.panelVendedores;
import Tipografia.Fuente;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import paneles.CambiaPanel;

/**
 *
 * @author Los Pibes
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    Fuente tipoFuente;

    public AdminDashboard() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        new CambiaPanel(panelContenedor, new panelInicio());
        tipoFuente = new Fuente();
        lbPunto.setVisible(true);
        lbPunto1.setVisible(false);
        lbPunto2.setVisible(false);
        lbPunto3.setVisible(false);
        lbPunto4.setVisible(false);
        lbUsuarioSesion.setText("       " + LoginAdmin.usuario.toUpperCase());

        btnAcerca.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        btnPeliculas.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        btnSalir.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        btnVendedores.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        btnInicio.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        btnHistorial.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 14));
        lbUsuarioSesion.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 11));
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cinematixLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new rojerusan.RSButtonMetro();
        btnPeliculas = new rojerusan.RSButtonMetro();
        btnVendedores = new rojerusan.RSButtonMetro();
        btnAcerca = new rojerusan.RSButtonMetro();
        btnSalir = new rojerusan.RSButtonMetro();
        btnHistorial = new rojerusan.RSButtonMetro();
        lbPunto = new javax.swing.JLabel();
        lbPunto1 = new javax.swing.JLabel();
        lbPunto2 = new javax.swing.JLabel();
        lbPunto3 = new javax.swing.JLabel();
        lbPunto4 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        lbImagenUsuario = new javax.swing.JLabel();
        lbUsuarioSesion = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(61, 61, 61));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoInicio.png"))); // NOI18N
        btnInicio.setText("   INICIO");
        btnInicio.setBorderPainted(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setSelected(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 248, 190, 26));

        btnPeliculas.setBackground(new java.awt.Color(61, 61, 61));
        btnPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoPelicula.png"))); // NOI18N
        btnPeliculas.setText("   PELICULAS");
        btnPeliculas.setBorderPainted(false);
        btnPeliculas.setFocusPainted(false);
        btnPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeliculas.setSelected(true);
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 304, 190, 26));

        btnVendedores.setBackground(new java.awt.Color(61, 61, 61));
        btnVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoVendedores.png"))); // NOI18N
        btnVendedores.setText("   VENDEDORES");
        btnVendedores.setBorderPainted(false);
        btnVendedores.setFocusPainted(false);
        btnVendedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVendedores.setSelected(true);
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 359, 190, 26));

        btnAcerca.setBackground(new java.awt.Color(61, 61, 61));
        btnAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAcerca.png"))); // NOI18N
        btnAcerca.setText("   ACERCA DE");
        btnAcerca.setBorderPainted(false);
        btnAcerca.setFocusPainted(false);
        btnAcerca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAcerca.setSelected(true);
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 472, 190, 26));

        btnSalir.setBackground(new java.awt.Color(61, 61, 61));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoSalir.png"))); // NOI18N
        btnSalir.setText("   SALIR");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setSelected(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 527, 190, 26));

        btnHistorial.setBackground(new java.awt.Color(61, 61, 61));
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoHistorial.png"))); // NOI18N
        btnHistorial.setText("   HISTORIAL");
        btnHistorial.setBorderPainted(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistorial.setSelected(true);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 414, 190, 26));

        lbPunto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoPunto.png"))); // NOI18N
        getContentPane().add(lbPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 257, -1, -1));

        lbPunto1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPunto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoPunto.png"))); // NOI18N
        getContentPane().add(lbPunto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 313, -1, -1));

        lbPunto2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPunto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoPunto.png"))); // NOI18N
        getContentPane().add(lbPunto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 369, -1, -1));

        lbPunto3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPunto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoPunto.png"))); // NOI18N
        getContentPane().add(lbPunto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 423, -1, -1));

        lbPunto4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPunto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoPunto.png"))); // NOI18N
        getContentPane().add(lbPunto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 480, -1, -1));

        panelContenedor.setBackground(new java.awt.Color(61, 61, 61));
        panelContenedor.setForeground(new java.awt.Color(61, 61, 61));
        panelContenedor.setOpaque(false);
        panelContenedor.setLayout(new javax.swing.BoxLayout(panelContenedor, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, 805, 690));

        lbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoUsuario.png"))); // NOI18N
        lbImagenUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbImagenUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbImagenUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbImagenUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbImagenUsuarioMouseExited(evt);
            }
        });
        getContentPane().add(lbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 655, -1, -1));

        lbUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuarioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/labelRedondeado.png"))); // NOI18N
        lbUsuarioSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbUsuarioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 655, 160, 24));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AdminDashboard1.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        if (Paneles.panelPeliculas.pantallaInfoAdicional != true) {
            new CambiaPanel(panelContenedor, new panelVendedores());
            lbPunto.setVisible(false);
            lbPunto1.setVisible(false);
            lbPunto2.setVisible(true);
            lbPunto3.setVisible(false);
        } else {
            ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoAdvertencia.png");
            JOptionPane.showMessageDialog(null, "Debe cerrar la pantalla de información adicional para continuar", "Advertencia", JOptionPane.PLAIN_MESSAGE, jPanelIcon);
        }
    }//GEN-LAST:event_btnVendedoresActionPerformed

    private void btnPeliculas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculas1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoPregunta.png");
        int ventanaConfirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, jPanelIcon);
        if (ventanaConfirmacion == 0) {
            Inicio ini = new Inicio();
            ini.setVisible(true);
            this.dispose();
        } else {

        }
        lbPunto.setVisible(false);
        lbPunto1.setVisible(false);
        lbPunto2.setVisible(false);
        lbPunto3.setVisible(false);
        lbPunto4.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        if (Paneles.panelPeliculas.pantallaInfoAdicional != true) {
            new CambiaPanel(panelContenedor, new panelAcercaDe());
            lbPunto.setVisible(false);
            lbPunto1.setVisible(false);
            lbPunto2.setVisible(false);
            lbPunto3.setVisible(false);
            lbPunto4.setVisible(true);
        } else {
            ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoAdvertencia.png");
            JOptionPane.showMessageDialog(null, "Debe cerrar la pantalla de información adicional para continuar", "Advertencia", JOptionPane.PLAIN_MESSAGE, jPanelIcon);
        }
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        new CambiaPanel(panelContenedor, new panelPeliculas());
        lbPunto.setVisible(false);
        lbPunto1.setVisible(true);
        lbPunto2.setVisible(false);
        lbPunto3.setVisible(false);
        lbPunto4.setVisible(false);
    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (Paneles.panelPeliculas.pantallaInfoAdicional != true) {
            new CambiaPanel(panelContenedor, new panelInicio());
            lbPunto.setVisible(true);
            lbPunto1.setVisible(false);
            lbPunto2.setVisible(false);
            lbPunto3.setVisible(false);
            lbPunto4.setVisible(false);
        } else {
            ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoAdvertencia.png");
            JOptionPane.showMessageDialog(null, "Debe cerrar la pantalla de información adicional para continuar", "Advertencia", JOptionPane.PLAIN_MESSAGE, jPanelIcon);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void lbImagenUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagenUsuarioMouseEntered
        //lbUsuarioSesion.setBounds(31, 655, 160, 24);
    }//GEN-LAST:event_lbImagenUsuarioMouseEntered

    private void lbImagenUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagenUsuarioMouseExited
        //lbUsuarioSesion.setBounds(31, 655, 15, 24);
    }//GEN-LAST:event_lbImagenUsuarioMouseExited

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        if (Paneles.panelPeliculas.pantallaInfoAdicional != true) {
            new CambiaPanel(panelContenedor, new panelHistorial());
            lbPunto.setVisible(false);
            lbPunto1.setVisible(false);
            lbPunto2.setVisible(false);
            lbPunto3.setVisible(true);
            lbPunto4.setVisible(false);
        } else {
            ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoAdvertencia.png");
            JOptionPane.showMessageDialog(null, "Debe cerrar la pantalla de información adicional para continuar", "Advertencia", JOptionPane.PLAIN_MESSAGE, jPanelIcon);
        }
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private rojerusan.RSButtonMetro btnAcerca;
    private rojerusan.RSButtonMetro btnHistorial;
    private rojerusan.RSButtonMetro btnInicio;
    private rojerusan.RSButtonMetro btnPeliculas;
    private rojerusan.RSButtonMetro btnSalir;
    private rojerusan.RSButtonMetro btnVendedores;
    private javax.swing.JLabel lbImagenUsuario;
    private javax.swing.JLabel lbPunto;
    private javax.swing.JLabel lbPunto1;
    private javax.swing.JLabel lbPunto2;
    private javax.swing.JLabel lbPunto3;
    private javax.swing.JLabel lbPunto4;
    private javax.swing.JLabel lbUsuarioSesion;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
