/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
 import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Reyes
 */
public class ConfirmarVenta extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarVenta
     */
    public ConfirmarVenta() {
       // setBackground(new Color(0, 0, 0, 0));
        super.setUndecorated(true);
        initComponents();
        noEditable();
        super.setLocationRelativeTo(this);
        jButtonComprar.setEnabled(false);
    }

    void noEditable() {
        jTextFieldPelicula.setEditable(false);
        jTextFieldHora.setEditable(false);
    }

    void calculo() {
        double efectivoR;
        double totalPago;
        double cambio;

        totalPago = Double.parseDouble(jLabelTotalPago.getText());
        efectivoR = Double.parseDouble(jTextFieldEfectivoRecibido.getText());
        if (efectivoR < totalPago) {
            JOptionPane.showMessageDialog(this, "No cuentas con suficiente dinero", "Cobro", JOptionPane.WARNING_MESSAGE);
        } else {
            cambio = efectivoR - totalPago;
            jLabelCambio.setText("L." + cambio + "0");
            jButtonComprar.setEnabled(true);
        }
    }

        void pasaDatos() {
        Ticket.jLabelPelicula.setText(jTextFieldPelicula.getText());
        Ticket.jLabelSala.setText(jLabelSala.getText());
        Ticket.jLabelTanda.setText(jTextFieldHora.getText());
        Ticket.jLabelNiños.setText(jTextFieldCantidadDeBoletosNiños.getText());
        Ticket.jLabeNiñosTotal.setText(jLabelTotalNiños.getText());
        Ticket.jLabeAdultos.setText(jTextFieldCantidadDeBoletosAdultos.getText());
        Ticket.jLabeAdultosTotal.setText(jLabelTotalAdultos.getText());
        Ticket.jLabeTotal.setText("L."+jLabelTotalPago.getText());
        Ticket.jLabeEfectivoRecibido.setText("L."+jTextFieldEfectivoRecibido.getText());
        Ticket.jLabeCambio.setText(jLabelCambio.getText());
        Ticket.jLabelISV.setText(jLabelImpuesto.getText());
    }
        
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cinematixLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresar = new rojerusan.RSButtonHover();
        jButtonComprar = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCantidadDeBoletosNiños = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotalPago = new javax.swing.JLabel();
        jTextFieldCantidadDeBoletosAdultos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotalNiños = new javax.swing.JLabel();
        jTextFieldPelicula = new javax.swing.JTextField();
        jLabelTotalAdultos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEfectivoRecibido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNombreVendedor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabelImpuesto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setBackground(new java.awt.Color(81, 81, 81));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoRegresar.png"))); // NOI18N
        jButtonRegresar.setText("REGRESAR");
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setColorHover(new java.awt.Color(61, 61, 61));
        jButtonRegresar.setFocusable(false);
        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 475, 140, 45));

        jButtonComprar.setBackground(new java.awt.Color(81, 81, 81));
        jButtonComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoComprar.png"))); // NOI18N
        jButtonComprar.setText("COMPRAR");
        jButtonComprar.setBorderPainted(false);
        jButtonComprar.setColorHover(new java.awt.Color(61, 61, 61));
        jButtonComprar.setFocusable(false);
        jButtonComprar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 475, 140, 45));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Niños");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pelicula ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad de boletos (niños)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 60, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("L.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Adultos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jTextFieldCantidadDeBoletosNiños.setEditable(false);
        jTextFieldCantidadDeBoletosNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeBoletosNiñosActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCantidadDeBoletosNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 50, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad de boletos (adultos)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sala");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabelSala.setBackground(new java.awt.Color(0, 204, 51));
        jLabelSala.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 20));

        jLabelTotalPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTotalPago.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelTotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 60, 20));

        jTextFieldCantidadDeBoletosAdultos.setEditable(false);
        jTextFieldCantidadDeBoletosAdultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeBoletosAdultosActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCantidadDeBoletosAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabelTotalNiños.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTotalNiños.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelTotalNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 50, 20));
        jPanel1.add(jTextFieldPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, -1));

        jLabelTotalAdultos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTotalAdultos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelTotalAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 20));

        jLabel9.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total a pagar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 104, 476, 360));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre vendedor: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tegucigalpa");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ubicacion:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Efectivo recibido:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextFieldEfectivoRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEfectivoRecibidoActionPerformed(evt);
            }
        });
        jTextFieldEfectivoRecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEfectivoRecibidoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldEfectivoRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 30));

        jLabel14.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cambio:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabelCambio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCambio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 60, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/click.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CineMatix");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jTextFieldNombreVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreVendedorActionPerformed(evt);
            }
        });
        jTextFieldNombreVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreVendedorKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 120, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ISV:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabelImpuesto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabelImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 104, 387, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ConfirmarPantalla.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldCantidadDeBoletosAdultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeBoletosAdultosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeBoletosAdultosActionPerformed

    private void jTextFieldCantidadDeBoletosNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeBoletosNiñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeBoletosNiñosActionPerformed

    private void jTextFieldEfectivoRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEfectivoRecibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEfectivoRecibidoActionPerformed

    private void jTextFieldEfectivoRecibidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEfectivoRecibidoKeyTyped
        char cant = evt.getKeyChar();

        if ((cant < '0' || cant > '9') && jTextFieldCantidadDeBoletosAdultos.getText().contains("")
                && (cant != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo se admiten numeros", "Validar numeros",
                     JOptionPane.WARNING_MESSAGE);

        } else if ((cant < '0' || cant > '9') && jTextFieldCantidadDeBoletosAdultos.getText().contains("")
                && (cant != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo se admiten numeros", "Validar numeros",
                     JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldEfectivoRecibidoKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double efectivoR;
        double isv;
        efectivoR = Double.parseDouble(jTextFieldEfectivoRecibido.getText());
        isv = efectivoR * 0.15;
        jLabelImpuesto.setText("L." + isv + "0");
        calculo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldNombreVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreVendedorActionPerformed

    private void jTextFieldNombreVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreVendedorKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten letras");
        }
    }//GEN-LAST:event_jTextFieldNombreVendedorKeyTyped

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        Ticket obj = new Ticket();
        pasaDatos();
        dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton3;
    public static rojerusan.RSButtonHover jButtonComprar;
    private rojerusan.RSButtonHover jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelImpuesto;
    public static final javax.swing.JLabel jLabelSala = new javax.swing.JLabel();
    public static javax.swing.JLabel jLabelTotalAdultos;
    public static javax.swing.JLabel jLabelTotalNiños;
    public static javax.swing.JLabel jLabelTotalPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jTextFieldCantidadDeBoletosAdultos;
    public static javax.swing.JTextField jTextFieldCantidadDeBoletosNiños;
    public static javax.swing.JTextField jTextFieldEfectivoRecibido;
    public static javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldNombreVendedor;
    public static javax.swing.JTextField jTextFieldPelicula;
    // End of variables declaration//GEN-END:variables
}
