/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Datos.Conexion;
import Tipografia.Fuente;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Los Pibes
 */
public class ControlSalas extends javax.swing.JFrame {

    /**
     * Creates new form ControlSalas
     */
    Fuente tipoFuente;
    log lo = new log();
    final Calendar calendar = Calendar.getInstance();
    final java.util.Date date = calendar.getTime();
    String fecha = new SimpleDateFormat("yyyyMMdd-hh.mm.ss").format(date);

    public ControlSalas() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        lbFS2D.setVisible(false);
        lbFS3D.setVisible(false);
        lbFSMax2D.setVisible(false);
        lbFSMax3D.setVisible(false);
        estadoSala2D();
        estadoSala3D();
        estadoSalaMax2D();
        estadoSalaMax3D();

        tipoFuente = new Fuente();
        lbDisponible2D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbReservado2D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbDisponible3D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbReservado3D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbDisponibleMax2D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbReservadoMax2D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbDisponibleMax3D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
        lbReservadoMax3D.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 22));
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cinematixLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDisponible2D = new javax.swing.JLabel();
        lbReservado2D = new javax.swing.JLabel();
        lbDisponible3D = new javax.swing.JLabel();
        lbReservado3D = new javax.swing.JLabel();
        lbDisponibleMax2D = new javax.swing.JLabel();
        lbReservadoMax3D = new javax.swing.JLabel();
        lbReservadoMax2D = new javax.swing.JLabel();
        lbDisponibleMax3D = new javax.swing.JLabel();
        lbFS2D = new javax.swing.JLabel();
        lbFS3D = new javax.swing.JLabel();
        lbFSMax2D = new javax.swing.JLabel();
        lbFSMax3D = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDisponible2D.setForeground(new java.awt.Color(255, 255, 255));
        lbDisponible2D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbDisponible2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 105, 50, 35));

        lbReservado2D.setForeground(new java.awt.Color(255, 255, 255));
        lbReservado2D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReservado2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 155, 50, 35));

        lbDisponible3D.setForeground(new java.awt.Color(255, 255, 255));
        lbDisponible3D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbDisponible3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 105, 50, 35));

        lbReservado3D.setForeground(new java.awt.Color(255, 255, 255));
        lbReservado3D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReservado3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 155, 50, 35));

        lbDisponibleMax2D.setForeground(new java.awt.Color(255, 255, 255));
        lbDisponibleMax2D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbDisponibleMax2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 50, 35));

        lbReservadoMax3D.setForeground(new java.awt.Color(255, 255, 255));
        lbReservadoMax3D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReservadoMax3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 340, 50, 35));

        lbReservadoMax2D.setForeground(new java.awt.Color(255, 255, 255));
        lbReservadoMax2D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbReservadoMax2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 50, 35));

        lbDisponibleMax3D.setForeground(new java.awt.Color(255, 255, 255));
        lbDisponibleMax3D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbDisponibleMax3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 290, 50, 35));

        lbFS2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FS2D.png"))); // NOI18N
        getContentPane().add(lbFS2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 75, 350, 150));

        lbFS3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FS3D.png"))); // NOI18N
        getContentPane().add(lbFS3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 75, 350, 150));

        lbFSMax2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FSMax2D.png"))); // NOI18N
        getContentPane().add(lbFSMax2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 260, 350, 150));

        lbFSMax3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FSMax3D.png"))); // NOI18N
        getContentPane().add(lbFSMax3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 350, 150));

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/controlSalas.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
                lo.LogBitacora("Error al abrir ventana " + e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    Conexion cc = new Conexion();
    Connection cn = cc.GetConexion();

    void disponibles2D() {
        String sql = "SELECT COUNT(*) AS 'Disponibles' FROM asiento WHERE IDSalas = 1 AND IDEstado = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String disponibles = rs.getString("Disponibles");
                lbDisponible2D.setText(disponibles);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos disponibles " + e);
        }
    }

    void reservados2D() {
        String sql = "SELECT COUNT(*) AS 'Reservados' FROM asiento WHERE IDSalas = 1 AND IDEstado = 2";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String reservados = rs.getString("Reservados");
                lbReservado2D.setText(reservados);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos reservados" + e);
        }
    }

    void disponibles3D() {
        String sql = "SELECT COUNT(*) AS 'Disponibles' FROM asiento WHERE IDSalas = 2 AND IDEstado = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String disponibles = rs.getString("Disponibles");
                lbDisponible3D.setText(disponibles);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos disponibles " + e);
        }
    }

    void reservados3D() {
        String sql = "SELECT COUNT(*) AS 'Reservados' FROM asiento WHERE IDSalas = 2 AND IDEstado = 2";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String reservados = rs.getString("Reservados");
                lbReservado3D.setText(reservados);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos reservados" + e);
        }
    }

    void disponiblesMax2D() {
        String sql = "SELECT COUNT(*) AS 'Disponibles' FROM asiento WHERE IDSalas = 3 AND IDEstado = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String disponibles = rs.getString("Disponibles");
                lbDisponibleMax2D.setText(disponibles);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos disponibles " + e);
        }
    }

    void reservadosMax2D() {
        String sql = "SELECT COUNT(*) AS 'Reservados' FROM asiento WHERE IDSalas = 3 AND IDEstado = 2";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String reservados = rs.getString("Reservados");
                lbReservadoMax2D.setText(reservados);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos reservados " + e);
        }
    }

    void disponiblesMax3D() {
        String sql = "SELECT COUNT(*) AS 'Disponibles' FROM asiento WHERE IDSalas = 4 AND IDEstado = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String disponibles = rs.getString("Disponibles");
                lbDisponibleMax3D.setText(disponibles);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos disponibles " + e);
        }
    }

    void reservadosMax3D() {
        String sql = "SELECT COUNT(*) AS 'Reservados' FROM asiento WHERE IDSalas = 4 AND IDEstado = 2";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String reservados = rs.getString("Reservados");
                lbReservadoMax3D.setText(reservados);
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener asientos reservados " + e);
        }
    }

    void estadoSala2D() {
        String deshabilitado = "2";
        String sql = "SELECT IDEstado FROM salas WHERE IDSalas = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String estado = rs.getString("IDEstado");
                if (estado.equals(deshabilitado)) {
                    lbFS2D.setVisible(true);
                } else {
                    disponibles2D();
                    reservados2D();
                }
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener el estado de los asientos " + e);
        }
    }

    void estadoSala3D() {
        String deshabilitado = "2";
        String sql = "SELECT IDEstado FROM salas WHERE IDSalas = 2";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String estado = rs.getString("IDEstado");
                if (estado.equals(deshabilitado)) {
                    lbFS3D.setVisible(true);
                } else {
                    disponibles3D();
                    reservados3D();
                }
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener el estado de los asientos " + e);
        }
    }

    void estadoSalaMax2D() {
        String deshabilitado = "2";
        String sql = "SELECT IDEstado FROM salas WHERE IDSalas = 3";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String estado = rs.getString("IDEstado");
                if (estado.equals(deshabilitado)) {
                    lbFSMax2D.setVisible(true);
                } else {
                    disponiblesMax2D();
                    reservadosMax2D();
                }
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener el estado de los asientos " + e);
        }
    }

    void estadoSalaMax3D() {
        String deshabilitado = "2";
        String sql = "SELECT IDEstado FROM salas WHERE IDSalas = 4";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String estado = rs.getString("IDEstado");
                if (estado.equals(deshabilitado)) {
                    lbFSMax3D.setVisible(true);
                } else {
                    disponiblesMax3D();
                    reservadosMax3D();
                }
            }

        } catch (Exception e) {
            lo.LogBitacora("Error al obtener el estado de los asientos " + e);
        }
    }

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
        MenuVendedor.pantallaControlSalas = false;
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel lbDisponible2D;
    private javax.swing.JLabel lbDisponible3D;
    private javax.swing.JLabel lbDisponibleMax2D;
    private javax.swing.JLabel lbDisponibleMax3D;
    private javax.swing.JLabel lbFS2D;
    private javax.swing.JLabel lbFS3D;
    private javax.swing.JLabel lbFSMax2D;
    private javax.swing.JLabel lbFSMax3D;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbReservado2D;
    private javax.swing.JLabel lbReservado3D;
    private javax.swing.JLabel lbReservadoMax2D;
    private javax.swing.JLabel lbReservadoMax3D;
    // End of variables declaration//GEN-END:variables
}
