package JFrames;

import Datos.Conexion;
import Tipografia.Fuente;
import encriptacion.Encode;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Los Pibes
 */
public class LoginPermisos extends javax.swing.JFrame {

    /**
     * Creates new form LoginVendedor
     */
    Fuente tipoFuente;
    log lo = new log();
    final Calendar calendar = Calendar.getInstance();
    final java.util.Date date = calendar.getTime();
    String fecha = new SimpleDateFormat("yyyyMMdd-hh.mm.ss").format(date);

    public LoginPermisos() {
        initComponents();
        transparenciaButton();
        setBackground(new Color(0, 0, 0, 0));
//        TextPrompt prueba = new TextPrompt("INGRESAR USUARIO", txtCorreo);
        TextPrompt pru = new TextPrompt("INGRESAR CLAVE", txtpassword);
        txtusuario.setText("adminprincipal");
        txtusuario.setEditable(false);
        setBackground(new Color(0, 0, 0, 0));

        tipoFuente = new Fuente();
        txtpassword.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 15));
        txtusuario.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 15));
//        prueba.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 15));
        pru.setFont(tipoFuente.fuente(tipoFuente.LUSI, 1, 15));
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cinematixLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btninicioa = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIconImage());
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btninicioa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnIniciarSesión.png"))); // NOI18N
        btninicioa.setBorderPainted(false);
        btninicioa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninicioa.setOpaque(false);
        btninicioa.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnIniciarSesión2.png"))); // NOI18N
        btninicioa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnIniciarSesión2.png"))); // NOI18N
        btninicioa.setVerifyInputWhenFocusTarget(false);
        btninicioa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioaActionPerformed(evt);
            }
        });
        getContentPane().add(btninicioa, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 404, 150, 40));

        txtusuario.setBackground(new java.awt.Color(0, 0, 0));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusuario.setBorder(null);
        txtusuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusuario.setOpaque(false);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, 240, 45));

        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCerrarFocusGained(evt);
            }
        });
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 90, 30, 30));

        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setOpaque(false);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 314, 240, 45));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginPermisos.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 508));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static String usuario;
    public boolean resultado = false;

    public boolean validarUsuario() {
        String secretKey = "lospibes";
        Encode encode = new Encode();
        Conexion cc = new Conexion();
        Connection cn = cc.GetConexion();
        String user = txtusuario.getText();
        String pass = String.valueOf(txtpassword.getPassword());
        String sql = "SELECT * FROM usuarios WHERE Usuario = '" + user + "'";

        if (txtusuario.getText().isEmpty() && txtpassword.getText().isEmpty() || txtusuario.getText().isEmpty() || txtpassword.getText().isEmpty()) {
            ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoAdvertencia.png");
            JOptionPane.showMessageDialog(null, "Debes llenar los campos", "Advertencia", JOptionPane.PLAIN_MESSAGE, jPanelIcono);

        } else {
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);

                if (rs.next()) {
                    usuario = rs.getString("Usuario");
                    int intentos = Integer.parseInt(rs.getString("Intentos"));
                    if (rs.getString("Intentos").equals("0")) {
                        ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoSalida.png");
                        JOptionPane.showMessageDialog(null, "Usuario inactivo, comuniquese con el administrador del sistema para restablecer su usuario", "Acceso denegado", JOptionPane.PLAIN_MESSAGE, jPanelIcono);
                        txtpassword.setText("");

                    } else if (encode.deecnode(secretKey, rs.getString("Contrasena")).equals(pass)) {
                        resultado = true;
                        Permisos p = new Permisos();
                        p.setVisible(true);
                        this.dispose();
                        try {
                            String sqlRestar = "UPDATE `usuarios` SET `Intentos` = ? WHERE `usuarios`.`Usuario` = ? ";
                            PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sqlRestar);
                            pst.setString(1, String.valueOf("3"));
                            pst.setString(2, user);
                            pst.execute();

                        } catch (Exception e) {
                            lo.LogBitacora("No ha sido posible restar los intentos " + e);
                            ImageIcon jPanelIcon = new ImageIcon("src/iconos/iconoError.png");
                            JOptionPane.showMessageDialog(null, "No ha sido posible restar los intentos" + e, "Error", JOptionPane.PLAIN_MESSAGE, jPanelIcon);
                        }
                    } else {
                        --intentos;
                        if (intentos == 0) {
                            ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoError.png");
                            JOptionPane.showMessageDialog(null, "Ha excedido el número de intentos para ingresar \n" + "Su usuario ha sido deshabilitado", "Acceso denegado", JOptionPane.PLAIN_MESSAGE, jPanelIcono);
                            txtusuario.setText("");
                            txtpassword.setText("");
                            Inicio inicio = new Inicio();
                            inicio.setVisible(true);
                            this.dispose();
                            try {
                                String sqlEstado = "UPDATE `usuarios` SET `Intentos` = ? WHERE `usuarios`.`Usuario` = ? ";
                                PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sqlEstado);
                                pst.setString(1, String.valueOf(intentos));
                                pst.setString(2, user);
                                pst.execute();

                            } catch (Exception e) {
                                lo.LogBitacora("Ha excedido el número de intentos para ingresar  " + e);
                                
                            }
                        } else {
                            try {
                                String sqlEstado = "UPDATE `usuarios` SET `Intentos` = ? WHERE `usuarios`.`Usuario` = ? ";
                                PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sqlEstado);
                                pst.setString(1, String.valueOf(intentos));
                                pst.setString(2, user);
                                pst.execute();

                            } catch (Exception e) {
                               lo.LogBitacora("Usuario o clave incorrecta  " + e);
                            }
                            ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoAdvertencia.png");
                            JOptionPane.showMessageDialog(null, "Usuario o clave incorrecta, te quedan " + intentos + " intentos", "Adveretencia", JOptionPane.PLAIN_MESSAGE, jPanelIcono);
                            txtpassword.setText("");
                        }
                    }
                } else {
                    ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoAdvertencia.png");
                    JOptionPane.showMessageDialog(null, "Asegurate de usar un usuario y una contraseña correctos", "Adveretencia", JOptionPane.PLAIN_MESSAGE, jPanelIcono);
                }

            } catch (Exception e) {
              lo.LogBitacora("Asegurate de usar un usuario y una contraseña correctos" + e);
                ImageIcon jPanelIcono = new ImageIcon("src/iconos/iconoSalida.png");
                JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión", "Error", JOptionPane.PLAIN_MESSAGE, jPanelIcono);
                System.out.println(e.getMessage());
                txtusuario.setText("");
                txtpassword.setText("");
            }
        }
        return resultado;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
               lo.LogBitacora("Error al abrir la ventana " + e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    public void transparenciaButton() {
        btninicioa.setOpaque(false);
        btninicioa.setContentAreaFilled(false);
        btninicioa.setBorderPainted(false);
    }

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        Inicio regresoMenu = new Inicio();
        regresoMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCerrarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarFocusGained

    private void btninicioaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioaActionPerformed
        validarUsuario();
    }//GEN-LAST:event_btninicioaActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validarUsuario();
        }
    }//GEN-LAST:event_txtpasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPermisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPermisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPermisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPermisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPermisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btninicioa;
    private javax.swing.JLabel labelFondo;
    public javax.swing.JPasswordField txtpassword;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
